name: 'unesp_analytics'
version: '1.0.0'

profile: 'unesp_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  unesp_analytics:
    staging:
      +materialized: view
      +schema: analytics

    marts:
      +materialized: table
      +schema: analytics
      
    analytics:
      +materialized: view
      +schema: analytics